
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artisan-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artisan-app
  template:
    metadata:
      labels:
        app: artisan-app   # Pod label
    spec:
      containers:
        - name: artisan-app
          image: jackedu/artisan_app:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: artisan-app-svc
spec:
  selector:
    app: artisan-app      # Matches pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
