grafana:
  adminPassword: "ThisIsATestPassword654@"   # Sets Grafana admin login password
  service:
    type: ClusterIP                         # Expose via Ingress or port-forward
  nodeSelector:
    role: monitoring_node                   # Schedule only on monitoring nodes
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true             # Required for /grafana path
    analytics:
      check_for_updates: true
    log:
      mode: console
    paths:
      data: /var/lib/grafana
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning

prometheus:
  service:
    type: ClusterIP                         # Internal service type
  prometheusSpec:                           
    replicas: 1
    nodeSelector:
      role: monitoring_node                 # Schedule only on monitoring nodes
    retention: 15d                          # Keep metrics data for 15 days
    storageSpec:                            
      volumeClaimTemplate:                  
        spec:  
          storageClassName: gp2                             
          accessModes: ["ReadWriteOnce"]    # Volume mounted by one node at a time
          resources:                        
            requests:
              storage: 20Gi                 # Allocate 20Gi of persistent storage
