version: "3.8"

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_docker_data:/var/lib/docker  # If you don’t persist it, all Docker images built inside D-in-D will be lost when the container restarts. That’s usually fine for CI/CD jobs that rebuild images every time.
      - jenkins-docker-certs:/certs/client   # Shared volume for Docker TLS certificates
    ports:
      - 2376:2376
    networks:
      jenkins:
        aliases:
          - docker
    command: --storage-driver overlay2


  my-jenkins:
    image: my-jenkins
    build:
      context: .
    container_name: my-jenkins
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - /home/ec2-user/jenkins_install:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro   # Mount the certs directory (read-only) so Jenkins can authenticate to Docker
    ports:
      - "8080:8080"
      - "50000:50000"  # Jenkins agents (JNLP)
    networks:
      - jenkins
  

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    restart: unless-stopped
    depends_on:
      - sonar_db
    ports:
      - "9001:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - jenkins

  # Postgres for SonarQube
  sonar_db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql/data
    networks:
      - jenkins


networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_docker_data:
  jenkins-docker-certs:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  